use super::*;
use crate::api::DashboardTerminalProjectionSlice;
use serde_json::json;
use std::sync::LazyLock;

pub(crate) mod part_01;
mod part_02;
mod part_03;
mod part_04;
mod part_05;
mod part_06;
mod part_07;
mod part_08;
mod part_09;
mod part_10;
mod part_11;
mod part_12;
mod part_13;
mod part_14;
mod part_15;
mod part_16;
mod part_17;
mod part_18;
mod part_19;
mod part_20;
mod part_21;
mod part_22;
mod part_23;
mod part_24;

pub(crate) use part_01::*;
pub(crate) use part_02::*;
pub(crate) use part_03::*;
pub(crate) use part_04::*;
pub(crate) use part_05::*;
pub(crate) use part_06::*;
pub(crate) use part_07::*;
pub(crate) use part_08::*;
pub(crate) use part_09::*;
pub(crate) use part_10::*;
pub(crate) use part_11::*;
pub(crate) use part_12::*;
pub(crate) use part_13::*;
pub(crate) use part_14::*;
pub(crate) use part_15::*;
pub(crate) use part_16::*;
pub(crate) use part_17::*;
pub(crate) use part_18::*;
pub(crate) use part_19::*;
pub(crate) use part_20::*;
pub(crate) use part_21::*;
pub(crate) use part_22::*;
pub(crate) use part_23::*;
pub(crate) use part_24::*;
