pub(crate) struct PreAttemptProxyCaptureError<'a> {
    pub(crate) state: Arc<AppState>,
    pub(crate) proxy_request_id: u64,
    pub(crate) capture_started: Instant,
    pub(crate) invoke_id: &'a str,
    pub(crate) occurred_at: &'a str,
    pub(crate) capture_target: ProxyCaptureTarget,
    pub(crate) request_info: &'a RequestCaptureInfo,
    pub(crate) requester_ip: Option<&'a str>,
    pub(crate) request_chain_metadata: &'a RequestChainMetadata,
    pub(crate) sticky_key: Option<&'a str>,
    pub(crate) prompt_cache_key: Option<&'a str>,
    pub(crate) client_attribution_context: &'a ClientPromptCacheAttributionContext,
    pub(crate) request_body_for_capture: Option<Bytes>,
    pub(crate) request_body_snapshot: PoolReplayBodySnapshot,
    pub(crate) request_body_logging_enabled: bool,
    pub(crate) t_req_read_ms: f64,
    pub(crate) t_req_parse_ms: f64,
    pub(crate) status: StatusCode,
    pub(crate) failure_kind: &'static str,
    pub(crate) error_message: &'a str,
    pub(crate) terminal_attempt_summary: Option<&'a PoolAttemptSummary>,
    pub(crate) terminal_account: Option<&'a PoolResolvedAccount>,
    pub(crate) terminal_connect_latency_ms: Option<f64>,
    pub(crate) terminal_error: Option<&'a PoolUpstreamError>,
    pub(crate) terminal_request_compression_algorithm: Option<&'a str>,
    pub(crate) response_envelope_override: Option<ProxyErrorResponseEnvelope>,
}

fn build_pre_attempt_proxy_capture_payload<'a>(
    request: &'a PreAttemptProxyCaptureError<'a>,
) -> ProxyPayloadSummary<'a> {
    let request_info = request.request_info;
    let request_chain = request.request_chain_metadata;
    let account = request.terminal_account;
    let error = request.terminal_error;
    let summary = request.terminal_attempt_summary;
    ProxyPayloadSummary {
        target: request.capture_target,
        status: request.status,
        is_stream: request_info.is_stream,
        request_contains_encrypted_content: request_info.contains_encrypted_content,
        response_contains_encrypted_content: false,
        compaction_request_kind: request_info.compaction_request_kind,
        compaction_response_kind: None,
        image_intent: request_info.image_intent.as_deref(),
        request_model: request_info.model.as_deref(),
        requested_service_tier: request_info.requested_service_tier.as_deref(),
        billing_service_tier: None,
        reasoning_effort: request_info.reasoning_effort.as_deref(),
        response_model: None,
        usage_missing_reason: None,
        request_parse_error: request_info.parse_error.as_deref(),
        request_compression_algorithm: request.terminal_request_compression_algorithm,
        request_compression_mode: None,
        request_compression_logical_body_bytes: None,
        request_compression_transmitted_body_bytes: None,
        request_compression_transmission_complete: None,
        failure_kind: Some(request.failure_kind),
        requester_ip: request.requester_ip,
        request_user_agent: request_chain.user_agent.as_deref(),
        request_x_forwarded_for: request_chain.x_forwarded_for.as_deref(),
        request_forwarded: request_chain.forwarded.as_deref(),
        request_x_real_ip: request_chain.x_real_ip.as_deref(),
        upstream_scope: INVOCATION_UPSTREAM_SCOPE_INTERNAL,
        route_mode: INVOCATION_ROUTE_MODE_POOL,
        sticky_key: request.sticky_key,
        prompt_cache_key: request.prompt_cache_key,
        prompt_cache_key_attribution_source: request_info
            .prompt_cache_key_attribution_source
            .as_deref(),
        client_fingerprint: request.client_attribution_context.fingerprint.as_deref(),
        client_header_fingerprints: Some(&request.client_attribution_context.header_fingerprints)
            .filter(|fingerprints| !fingerprints.is_empty()),
        upstream_account_id: account.map(|account| account.account_id),
        upstream_account_name: account.map(|account| account.display_name.as_str()),
        upstream_account_kind: account.map(|account| account.kind.as_str()),
        upstream_base_url_host: account.and_then(|account| account.upstream_base_url.host_str()),
        oauth_account_header_attached: None,
        oauth_account_id_shape: None,
        oauth_forwarded_header_count: None,
        oauth_forwarded_header_names: None,
        oauth_fingerprint_version: None,
        oauth_forwarded_header_fingerprints: None,
        oauth_prompt_cache_header_forwarded: None,
        oauth_request_body_prefix_fingerprint: None,
        oauth_request_body_prefix_bytes: None,
        oauth_request_body_snapshot_kind: None,
        oauth_responses_body_mode: None,
        oauth_responses_rewrite: None,
        service_tier: None,
        stream_terminal_event: None,
        upstream_error_code: error.and_then(|error| error.upstream_error_code.as_deref()),
        upstream_error_message: error.and_then(|error| error.upstream_error_message.as_deref()),
        downstream_status_code: Some(request.status),
        downstream_error_message: Some(request.error_message),
        upstream_request_id: error.and_then(|error| error.upstream_request_id.as_deref()),
        response_content_encoding: None,
        stream_failure_origin: None,
        upstream_read_error_kind: None,
        content_encoding_chain: None,
        forwarded_chunk_count: None,
        forwarded_bytes: None,
        usage_observed: None,
        downstream_close_phase: None,
        downstream_write_error_kind: None,
        last_upstream_chunk_gap_ms: None,
        upstream_approx_upload_bytes: None,
        upstream_approx_download_bytes: None,
        proxy_display_name: None,
        proxy_weight_delta: None,
        pool_attempt_count: summary.map(|summary| summary.pool_attempt_count),
        pool_distinct_account_count: summary.map(|summary| summary.pool_distinct_account_count),
        pool_attempt_terminal_reason: summary
            .and_then(|summary| summary.pool_attempt_terminal_reason.as_deref())
            .or(Some(request.failure_kind)),
        blocked_binding: error.and_then(|error| error.blocked_binding.as_ref()),
    }
}
