INSERT OR IGNORE INTO codex_invocations (
    invoke_id,
    occurred_at,
    source,
    model,
    input_tokens,
    output_tokens,
    cache_input_tokens,
    reasoning_tokens,
    total_tokens,
    cost,
    cost_input,
    cost_cache_write,
    cost_cache_read,
    cost_output,
    cost_reasoning,
    cost_estimated,
    price_version,
    status,
    error_message,
    failure_kind,
    failure_class,
    is_actionable,
    payload,
    raw_response,
    request_raw_path,
    request_raw_codec,
    request_raw_size,
    request_raw_truncated,
    request_raw_truncated_reason,
    response_raw_path,
    response_raw_codec,
    response_raw_size,
    response_raw_truncated,
    response_raw_truncated_reason,
    t_total_ms,
    t_req_read_ms,
    t_req_parse_ms,
    t_upstream_connect_ms,
    t_upstream_ttfb_ms,
    first_token_ms,
    t_upstream_stream_ms,
    t_resp_parse_ms,
    t_persist_ms,
    created_at
)
VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19,
    ?20, ?21, ?22, ?23, ?24, ?25, ?26, ?27, ?28, ?29, ?30, ?31, ?32, ?33, ?34, ?35, ?36,
    ?37, ?38, ?39, ?40, ?41, ?42, ?43, ?44
)
