struct SummaryProjectionBuildArchiveHydrationInput<'a> {
    pool: &'a Pool<Sqlite>,
    mode: SummaryProjectionBuildMode,
    archive_start: DateTime<Utc>,
    end: DateTime<Utc>,
    exact_horizon: ExactUtcRange,
    build_started_at: Instant,
    archives: Vec<crate::stats::ArchiveBatchPathRow>,
    paged_boundary_manifest_high_watermark_id: Option<i64>,
    archive_replay_coverage: &'a HashMap<String, SummaryProjectionArchiveReplayCoverage>,
    archive_row_counts: &'a HashMap<String, i64>,
    archive_manifest_sha256: &'a HashMap<String, String>,
    hourly_rollup_totals: &'a HashMap<(i64, Option<i64>), StatsTotals>,
    hourly_rollup_usage: &'a HashMap<(i64, Option<i64>), UsageBreakdownResponse>,
    exact_archive_buckets: &'a HashSet<i64>,
    protected_boundary_buckets: &'a HashSet<i64>,
    exact_bucket_requirements: &'a HashSet<i64>,
    usage_rollup_progress: &'a HashMap<String, i64>,
    known_account_ids: &'a HashSet<i64>,
    persisted_live_ids: &'a HashSet<SummarySourceIdentity>,
    current_record_bytes: usize,
    records_by_invoke_id: &'a mut HashMap<String, SummaryProjectionRecord>,
    exact_record_budget: &'a mut usize,
    exact_record_bytes: &'a mut usize,
    unavailable_unmaterialized_archive_buckets: &'a mut BTreeSet<i64>,
    unavailable_boundary_archive_ranges: &'a mut Vec<ExactUtcRange>,
    unavailable_unmaterialized_archive_current_ranges: &'a mut Vec<ExactUtcRange>,
    all_time_source_unavailable_from_archive_ranges: &'a mut bool,
}

async fn hydrate_summary_projection_build_archives(
    input: SummaryProjectionBuildArchiveHydrationInput<'_>,
) -> Result<()> {
    let SummaryProjectionBuildArchiveHydrationInput {
        pool,
        mode,
        archive_start,
        end,
        exact_horizon,
        build_started_at,
        archives,
        paged_boundary_manifest_high_watermark_id,
        archive_replay_coverage,
        archive_row_counts,
        archive_manifest_sha256,
        hourly_rollup_totals,
        hourly_rollup_usage,
        exact_archive_buckets,
        protected_boundary_buckets,
        exact_bucket_requirements,
        usage_rollup_progress,
        known_account_ids,
        persisted_live_ids,
        current_record_bytes,
        records_by_invoke_id,
        exact_record_budget,
        exact_record_bytes,
        unavailable_unmaterialized_archive_buckets,
        unavailable_boundary_archive_ranges,
        unavailable_unmaterialized_archive_current_ranges,
        all_time_source_unavailable_from_archive_ranges,
    } = input;
    hydrate_summary_projection_boundary_archives(
        SummaryProjectionBoundaryArchiveHydrationState {
            pool,
            mode,
            archive_start,
            end,
            build_started_at,
            archive_replay_coverage,
            archive_row_counts,
            archive_manifest_sha256,
            hourly_rollup_totals,
            hourly_rollup_usage,
            exact_archive_buckets,
            exact_bucket_requirements,
            usage_rollup_progress,
            known_account_ids,
            persisted_live_ids,
            current_record_bytes,
            records_by_invoke_id,
            exact_record_budget,
            exact_record_bytes,
            unavailable_unmaterialized_archive_buckets,
            unavailable_boundary_archive_ranges,
            unavailable_unmaterialized_archive_current_ranges,
            all_time_source_unavailable_from_archive_ranges,
        },
        archives,
    )
    .await?;
    hydrate_summary_projection_paged_boundary_archives(
        SummaryProjectionPagedBoundaryHydrationInput {
            pool,
            mode,
            exact_horizon,
            build_started_at,
            paged_boundary_manifest_high_watermark_id,
            exact_archive_buckets,
            protected_boundary_buckets,
            exact_bucket_requirements,
            hourly_rollup_totals,
            hourly_rollup_usage,
            persisted_live_ids,
            current_record_bytes,
            records_by_invoke_id,
            exact_record_budget,
            exact_record_bytes,
            unavailable_unmaterialized_archive_buckets,
            unavailable_boundary_archive_ranges,
            unavailable_unmaterialized_archive_current_ranges,
        },
    )
    .await?;
    Ok(())
}
