struct SummaryProjectionFinalizationInput<'a> {
    state: &'a AppState,
    pool: &'a Pool<Sqlite>,
    mode: SummaryProjectionBuildMode,
    build_started_at: Instant,
    exact_horizon: ExactUtcRange,
    all_time_was_fully_rebuilt: bool,
    rebuilt_all_time_account_ids: HashSet<i64>,
    previous_all_time_refreshed_at: Option<Instant>,
    previous_all_time_manifest_admission_blocked_at: Option<Instant>,
    previous_all_time_account_manifest_admission_blocked_at: Option<Instant>,
    previous_global_all_time_eligible: bool,
    previous_account_all_time_eligible: HashSet<i64>,
    previous_global_all_time_coverage_fence: Option<SummaryCoverageFence>,
    previous_account_all_time_coverage_fence: Option<SummaryCoverageFence>,
    previous_all_time_terminal_coverage_complete: bool,
    previous_all_time_terminal_sequence_watermark: u64,
    previous_all_time_account_terminal_sequence_watermarks: HashMap<i64, u64>,
    previous_all_time_account_persisted_live_terminal_invoke_ids: HashMap<i64, HashSet<String>>,
    all_time_archive_admission_exceeded: bool,
    all_time_account_manifest_admission_attempted: bool,
    all_time_account_manifest_admission_exceeded: bool,
    all_time_account_refreshed_at: HashMap<i64, Instant>,
    all_time_by_account: HashMap<Option<i64>, StatsResponse>,
    global_all_time_source_unavailable: bool,
    account_all_time_unavailable: bool,
    historical_global_covered_terminal_invoke_ids: HashSet<String>,
    durable_terminal_sequence_watermark: u64,
    live_high_watermark_id: i64,
    account_rollup_live_cursor: Option<i64>,
    completed_manifest_high_watermark_id: Option<i64>,
    records: Vec<SummaryProjectionRecord>,
    current_records: Vec<SummaryProjectionRecord>,
    hourly_buckets: BTreeMap<i64, Vec<usize>>,
    recent_indexes: HashMap<Option<i64>, Vec<usize>>,
    recent_index_complete: bool,
    recent_index_overflow_at: Option<DateTime<Utc>>,
    hourly_rollup_totals: HashMap<(i64, Option<i64>), StatsTotals>,
    hourly_rollup_non_success_tokens: HashMap<(i64, Option<i64>), i64>,
    hourly_rollup_usage: HashMap<(i64, Option<i64>), UsageBreakdownResponse>,
    exact_global_total_rollup_buckets: HashSet<i64>,
    exact_account_total_rollup_buckets: HashSet<i64>,
    exact_global_usage_rollup_buckets: HashSet<i64>,
    exact_account_usage_rollup_buckets: HashSet<i64>,
    rollup_live_cursor: i64,
    historical_live_coverage: Option<SummaryProjectionHistoricalLiveCoverage>,
    previous_coverage_overlay: Option<SummaryCoverageOverlay>,
    account_ids_with_projection_data: HashSet<i64>,
    account_ids: HashSet<i64>,
    archive_account_ids_by_file: HashMap<String, HashSet<i64>>,
    archive_actual_coverage_ranges: HashMap<String, ExactUtcRange>,
    unavailable_unmaterialized_archive_buckets: BTreeSet<i64>,
    unavailable_unmaterialized_archive_exact_ranges: Vec<ExactUtcRange>,
    unavailable_boundary_archive_ranges: Vec<ExactUtcRange>,
    unavailable_unmaterialized_archive_current_ranges: Vec<ExactUtcRange>,
    unavailable_unmaterialized_archive_account_buckets: BTreeSet<i64>,
    unavailable_unmaterialized_archive_account_exact_ranges: Vec<ExactUtcRange>,
    unavailable_boundary_archive_account_ranges: Vec<ExactUtcRange>,
    unavailable_unmaterialized_archive_account_current_ranges: Vec<ExactUtcRange>,
    unavailable_exact_live_buckets: BTreeSet<i64>,
    unavailable_exact_live_account_buckets: HashMap<i64, BTreeSet<i64>>,
    current_complete_archive_paths: HashSet<String>,
    current_source_unavailable: bool,
    current_source_unavailable_from_rank: Option<usize>,
    current_account_source_unavailable_from_rank: HashMap<i64, usize>,
    current_archive_admission_exceeded: bool,
    in_progress_by_account: HashMap<Option<i64>, InProgressSummarySnapshot>,
    maintenance: StatsMaintenanceResponse,
}

async fn finalize_summary_projection(
    input: SummaryProjectionFinalizationInput<'_>,
) -> Result<SummaryProjection> {
    let context = prepare_summary_projection_finalization(input).await?;
    finish_summary_projection_finalization(context).await
}
